version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ecokitoto
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: ecokitoto
    ports:
      - "5432:5432"